services:
  - type: web
    name: homefinder
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: GOOGLE_CHROME_BIN
        value: /usr/bin/google-chrome-stable
      - key: CHROMEDRIVER_PATH
        value: /usr/bin/chromedriver
